language: node_js

node_js:
  - 12

addons:
  code_climate:
    repo_token: b04bcf6ebc70567672c834d14acc6eab1ddb5b2fe1cfa62d9d1d421010a0ce31
  apt:
    packages:
      - libgconf-2-4

services:
  - xvfb

before_install:
  - export NG_CLI_ANALYTICS=ci

install:
  - npm ci
  - npm install codeclimate-test-reporter
  - npm run build
  - npm run build:lib:prod

script:
  - npm run ci

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
